/**
 * Core type definitions mirroring React Navigation's internal state shape.
 * These intentionally match the objects you would get back from
 * `navigation.getState()` in a real app (v6 and v7 share this shape).
 */

export type NavigatorType = 'stack' | 'tab' | 'drawer';

/**
 * Controls what a tab/drawer navigator does with GO_BACK.
 * Documented values; `firstRoute` is the default for BOTH bottom tabs and
 * the drawer (the drawer does not default to `history`).
 */
export type BackBehavior = 'firstRoute' | 'initialRoute' | 'order' | 'history' | 'fullHistory' | 'none';

/** Which major version of React Navigation the engine should emulate. */
export type RNVersion = 'v6' | 'v7';

export type Params = Record<string, unknown>;

/** A single entry in `state.routes`. */
export interface RouteState {
  /** Auto-generated by the library: `${name}-${uniqueId}`. Identifies the component instance. */
  key: string;
  name: string;
  params?: Params;
  /** Present once a nested navigator inside this route has mounted. */
  state?: NavState;
}

/** History entry used by tab/drawer routers to implement `backBehavior`. */
export type HistoryEntry =
  | { type: 'route'; key: string }
  | { type: 'drawer'; status: 'open' };

/** The shape returned by `navigation.getState()`. */
export interface NavState {
  key: string;
  type: NavigatorType;
  index: number;
  /** Every screen declared on the navigator, even if not yet in `routes`. */
  routeNames: string[];
  routes: RouteState[];
  history?: HistoryEntry[];
  /** Always false for a live (non-rehydrated) state object. */
  stale: false;
}

/* ------------------------------------------------------------------ */
/* Actions                                                             */
/* ------------------------------------------------------------------ */

export type NavAction =
  | { type: 'NAVIGATE'; payload: { name: string; params?: Params; merge?: boolean; pop?: boolean } }
  /** v7 escape hatch that reproduces the v6 `navigate` semantics verbatim. */
  | { type: 'NAVIGATE_DEPRECATED'; payload: { name: string; params?: Params; merge?: boolean } }
  | { type: 'PUSH'; payload: { name: string; params?: Params } }
  | { type: 'POP'; payload: { count: number } }
  /** v7 only. */
  | { type: 'POP_TO'; payload: { name: string; params?: Params; merge?: boolean } }
  | { type: 'POP_TO_TOP' }
  | { type: 'REPLACE'; payload: { name: string; params?: Params } }
  | { type: 'RESET'; payload: { routeNames?: string[]; index: number; routes: Array<{ name: string; params?: Params }> } }
  | { type: 'GO_BACK' }
  | { type: 'SET_PARAMS'; payload: { params: Params } }
  /** v7: replaces route.params outright instead of shallow-merging. */
  | { type: 'REPLACE_PARAMS'; payload: { params: Params } }
  | { type: 'JUMP_TO'; payload: { name: string; params?: Params } }
  | { type: 'OPEN_DRAWER' }
  | { type: 'CLOSE_DRAWER' }
  | { type: 'TOGGLE_DRAWER' };

export type ActionType = NavAction['type'];

/* ------------------------------------------------------------------ */
/* Engine options & results                                            */
/* ------------------------------------------------------------------ */

export interface EngineOptions {
  version: RNVersion;
  /**
   * v6 behaviour (and v7 with `<NavigationContainer navigationInChildEnabled />`):
   * an unhandled NAVIGATE may be resolved by a *mounted child* navigator.
   * Removed as a default in v7.
   */
  navigationInChildEnabled: boolean;
  /**
   * When true, `popTo` refuses to instantiate a screen that is not already in
   * the stack and raises a simulation error instead. This is a teaching mode:
   * the real v7 `popTo` pops the current screen and pushes the target.
   */
  strictPopTo: boolean;
}

/** Why a given route key disappeared or survived — powers the UI tooltips. */
export interface RouteVerdict {
  key: string;
  name: string;
  outcome: 'added' | 'removed' | 'kept' | 'params-updated' | 'refocused';
  reason: string;
}

export interface DispatchResult {
  state: NavState;
  /** Key of the navigator that actually consumed the action. */
  handledBy: string | null;
  /** Navigator keys the action travelled through before being handled. */
  bubblePath: string[];
  /** Human-readable, mechanically accurate explanation of what the router did. */
  rationale: string;
  error?: string;
  verdicts: RouteVerdict[];
  /** e.g. "v7: navigate() pushed instead of unwinding" */
  versionNote?: string;
}

/* ------------------------------------------------------------------ */
/* Lifecycle                                                           */
/* ------------------------------------------------------------------ */

export type LifecycleKind = 'mount' | 'unmount' | 'focus' | 'blur';

export interface LifecycleEvent {
  kind: LifecycleKind;
  routeKey: string;
  routeName: string;
  /** The hook a developer would observe firing. */
  hook: 'useEffect' | 'useFocusEffect';
  detail: string;
}

export type LogLevel = 'action' | 'lifecycle' | 'error' | 'info' | 'warn';

export interface LogEntry {
  id: number;
  level: LogLevel;
  /** Monotonic tick, rendered like a timestamp in the console. */
  t: number;
  text: string;
  hook?: LifecycleEvent['hook'];
  kind?: LifecycleKind;
}
